### ISSUE TITLE
Allow using the package without having to have all these files in the same directory

### ISSUE THREAD

**Issue by amarz45** [DigitalKhatt/lualatexpackage#1]
First, thanks for such a great package. The resulting PDF looks great! However, It's kind of annoying having to have all of these Lua files in the same directory, it doesn't work if I put them in the texmf directory with `digitalkhatt.sty`, they must be in the current working directory. Is there a solution to this?

**Comment by amarz45** [comment]
I realized all I have to do is copy all the files to `~/texmf/tex/lualatex/digitalkhatt`, then copy the font file to `/usr/local/share/fonts` then copy the `.so` file to the current working directory. Sorry for the unnecessary issue.

**Comment by aminanan** [comment]
Glad it worked.
